In [1]:
import pandas as pd
class2 = pd.read_csv('./Data/class2.csv')


In [3]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

train_x = label_encoder.fit_transform(class2['class2'])
train_x

array([2, 2, 1, 0, 1, 0])

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is last chance.',
    'and if you do not have this chance.',
    'you will never get any chance.',
    'will you do get this one?',
    'please, get this chance'
]

vect = CountVectorizer()
vect.fit(corpus)
vect.vocabulary_

{'this': 13,
 'is': 7,
 'last': 8,
 'chance': 2,
 'and': 0,
 'if': 6,
 'you': 15,
 'do': 3,
 'not': 10,
 'have': 5,
 'will': 14,
 'never': 9,
 'get': 4,
 'any': 1,
 'one': 11,
 'please': 12}

In [13]:
vect.transform(['you will never get any chance.']).toarray()

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]])

In [14]:
vect = CountVectorizer(stop_words = ['and', 'is', 'please', 'this']).fit(corpus)

In [15]:
vect

CountVectorizer(stop_words=['and', 'is', 'please', 'this'])

In [16]:
vect.vocabulary_

{'last': 6,
 'chance': 1,
 'if': 5,
 'you': 11,
 'do': 2,
 'not': 8,
 'have': 4,
 'will': 10,
 'never': 7,
 'get': 3,
 'any': 0,
 'one': 9}

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
doc = ['I like machine learning', 'I love deep learning', 'I run everyday']
tfidf_vect = TfidfVectorizer(min_df = 1)
tfidf_mat = tfidf_vect.fit_transform(doc)
doc_dist = (tfidf_mat * tfidf_mat.T)
print(str(doc_dist.get_shape()[0]), str(doc_dist.get_shape()[1]))

3 3


In [26]:
doc_dist.toarray()

array([[1.      , 0.224325, 0.      ],
       [0.224325, 1.      , 0.      ],
       [0.      , 0.      , 1.      ]])

In [1]:
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
warnings.filterwarnings('ignore')
import gensim
from gensim.models import Word2Vec


In [3]:
sample = open('./Data/peter.txt', 'r', encoding = 'UTF-8')
s = sample.read()

In [5]:
f = s.replace('\n', " ")
data = []

In [7]:
for i in sent_tokenize(f):
    temp = []
    for j in word_tokenize(i):
        temp.append(j.lower())
    data.append(temp)

In [15]:
model1 = gensim.models.Word2Vec(data, min_count = 1, vector_size = 100, window = 5, sg = 0)
model1.wv.similarity('peter', 'wendy')

0.074393824

In [13]:
model1.wv.similarity('peter', 'hook')

0.02770985

In [14]:
model2 = gensim.models.Word2Vec(data, min_count = 1, vector_size = 100, window = 5, sg = 1)
model2.wv.similarity('peter', 'wendy')

0.40088683

In [16]:
model2.wv.similarity('peter', 'hook')

0.52016735

In [17]:
from gensim.test.utils import common_texts
from gensim.models import FastText

model = FastText('./Data/peter.txt', vector_size = 4, window = 3, min_count = 1, epochs = 10)


In [21]:
model.wv.similarity('peter', 'wendy')

0.4592452

In [22]:
model.wv.similarity('peter', 'hook')

0.043825686

In [25]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
plt.style.use('ggplot')
from sklearn.decomposition import PCA
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec



In [31]:
glove_file = datapath('/home/jhmoon/venvTORCH/torchPractice/nlpPractice/Data/glove.6B.100d.txt')
word2vec_glove_file = get_tmpfile('/home/jhmoon/venvTORCH/torchPractice/nlpPractice/Data/glove.6B.100d.word2vec.txt')
glove2word2vec(glove_file, word2vec_glove_file)

(400000, 100)

In [32]:
model = KeyedVectors.load_word2vec_format(word2vec_glove_file)
model.most_similar('bill')

[('legislation', 0.8072139620780945),
 ('proposal', 0.730686366558075),
 ('senate', 0.7142541408538818),
 ('bills', 0.704440176486969),
 ('measure', 0.6958035230636597),
 ('passed', 0.690624475479126),
 ('amendment', 0.6846879720687866),
 ('provision', 0.6845567226409912),
 ('plan', 0.6816462874412537),
 ('clinton', 0.6663140058517456)]

In [33]:
model.most_similar(negative = ['bill'])

[('kilcoy', 0.5984036326408386),
 ('monterotondo', 0.5981862545013428),
 ('kilbarchan', 0.5969904065132141),
 ('aspendos', 0.5948131680488586),
 ('xidi', 0.5947748422622681),
 ('maxixe', 0.5914009809494019),
 ('dahon', 0.5868775248527527),
 ('shoeburyness', 0.578366756439209),
 ('saint-flour', 0.574941873550415),
 ('caffaro', 0.5744053721427917)]

In [34]:
result = model.most_similar(positive = ['woman','king'], negative = ['man'])
result[0]

('queen', 0.7698540687561035)

In [35]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive = [y1, x2], negative = [x1])
    return result[0][0]

In [36]:
analogy('australia', 'beer', 'france')

'champagne'

In [37]:
analogy('tall', 'tallest', 'long')

'longest'

In [38]:
model.doesnt_match('breakfast cereal dinner lunch'.split())

'cereal'