In [1]:
import nltk

In [2]:
nltk.data.path

['/home/jhmoon/nltk_data',
 '/home/jhmoon/venvTORCH/env/nltk_data',
 '/home/jhmoon/venvTORCH/env/share/nltk_data',
 '/home/jhmoon/venvTORCH/env/lib/nltk_data',
 '/usr/share/nltk_data',
 '/usr/local/share/nltk_data',
 '/usr/lib/nltk_data',
 '/usr/local/lib/nltk_data']

In [3]:
nltk.download("popular")

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /home/jhmoon/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to

True

In [4]:
text = nltk.word_tokenize("Is it possible distinguishing cats and dogs")

In [5]:
text

['Is', 'it', 'possible', 'distinguishing', 'cats', 'and', 'dogs']

In [6]:
nltk.pos_tag(text)

[('Is', 'VBZ'),
 ('it', 'PRP'),
 ('possible', 'JJ'),
 ('distinguishing', 'VBG'),
 ('cats', 'NNS'),
 ('and', 'CC'),
 ('dogs', 'NNS')]

In [7]:
string1 = "my favorite subject is math"
string2 = "my favorite subject is math, english, economic and computer science"
nltk.word_tokenize(string1)

['my', 'favorite', 'subject', 'is', 'math']

In [8]:
nltk.word_tokenize(string2)

['my',
 'favorite',
 'subject',
 'is',
 'math',
 ',',
 'english',
 ',',
 'economic',
 'and',
 'computer',
 'science']

In [9]:
from nltk import sent_tokenize

text_sample = 'Natural Language Processing, or NLP, is the process of extracting the meaning, or intent, behind human language. \
    In the field of Conversational artificial intelligence (AI), NLP allows machines and applications to understand the intent of \
        human language inputs, and then generate appropriate responses, resulting in a natural conversation flow.'

tokenized_sentences = sent_tokenize(text_sample)
print(tokenized_sentences)

['Natural Language Processing, or NLP, is the process of extracting the meaning, or intent, behind human language.', 'In the field of Conversational artificial intelligence (AI), NLP allows machines and applications to understand the intent of         human language inputs, and then generate appropriate responses, resulting in a natural conversation flow.']


In [10]:
from nltk import word_tokenize

sentence = "This book is for deep learning learners"
words = word_tokenize(sentence)
words

['This', 'book', 'is', 'for', 'deep', 'learning', 'learners']

In [12]:
from nltk import WordPunctTokenizer

sentence = "it's nothing that you don't already know except most people aren't aware of how their inner world works."
words = WordPunctTokenizer().tokenize(sentence)
words

['it',
 "'",
 's',
 'nothing',
 'that',
 'you',
 'don',
 "'",
 't',
 'already',
 'know',
 'except',
 'most',
 'people',
 'aren',
 "'",
 't',
 'aware',
 'of',
 'how',
 'their',
 'inner',
 'world',
 'works',
 '.']

In [13]:
from nltk.corpus import stopwords

sample_text = "One of the first things that we ask ourselves is what are the pros and cons of any task we perform."
text_tokens = word_tokenize(sample_text)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words('english')]
text_tokens

['One',
 'of',
 'the',
 'first',
 'things',
 'that',
 'we',
 'ask',
 'ourselves',
 'is',
 'what',
 'are',
 'the',
 'pros',
 'and',
 'cons',
 'of',
 'any',
 'task',
 'we',
 'perform',
 '.']

In [14]:
tokens_without_sw

['One', 'first', 'things', 'ask', 'pros', 'cons', 'task', 'perform', '.']

In [16]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
lemma.lemmatize('standardizes', 'v')

'standardize'

In [17]:
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]= "2"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")



In [40]:
df = pd.read_csv("./Data/diabetes.csv")
X = df[df.columns[:-1]]
y = df['Outcome']

In [41]:
X = X.values
y = torch.tensor(y.values)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33)

In [45]:
ms = MinMaxScaler()
ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)
y_train = ms.fit_transform(y_train)
y_test = ms.fit_transform(y_test)


In [47]:
class customDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.len = len(self.X)
    def __getitem__(self, index):
        return self.X[index], self.y[index]
    def __len__(self):
        return self.len

In [55]:
X_train

array([[-1.16444009, -0.56227168, -0.24430085, ...,  1.11957077,
         0.03679193, -1.02896448],
       [-1.16444009, -1.1107311 , -0.24430085, ...,  0.50619724,
         0.18390123, -1.02896448],
       [-0.24833467, -0.40992184, -0.34647387, ..., -1.14224411,
         0.58319791, -0.86360955],
       ...,
       [ 0.36240227, -0.13569213,  0.26656423, ...,  0.05894571,
         0.52915776,  0.12852003],
       [ 1.58387616,  1.50968613,  0.26656423, ...,  1.55404369,
        -0.24241552,  0.78993975],
       [ 2.80535005,  0.99169668,  0.98177534, ...,  1.11957077,
         2.07230431,  0.45922989]])

In [54]:
torch.FloatTensor(X_train)

tensor([[-1.1644, -0.5623, -0.2443,  ...,  1.1196,  0.0368, -1.0290],
        [-1.1644, -1.1107, -0.2443,  ...,  0.5062,  0.1839, -1.0290],
        [-0.2483, -0.4099, -0.3465,  ..., -1.1422,  0.5832, -0.8636],
        ...,
        [ 0.3624, -0.1357,  0.2666,  ...,  0.0589,  0.5292,  0.1285],
        [ 1.5839,  1.5097,  0.2666,  ...,  1.5540, -0.2424,  0.7899],
        [ 2.8054,  0.9917,  0.9818,  ...,  1.1196,  2.0723,  0.4592]])

In [57]:
train_data = customDataset(torch.FloatTensor(X_train), torch.FloatTensor(y_train))
test_data = customDataset(torch.FloatTensor(X_test), torch.FloatTensor(y_test))

In [58]:
train_loader = DataLoader(train_data, batch_size = 64, shuffle = True)
test_loader = DataLoader(test_data, batch_size = 64, shuffle = True)

In [59]:
class binaryClassification(nn.Module):
    def __init__(self):
        super(binaryClassification, self).__init__()
        self.layer1 = nn.Linear(8, 64, bias = True)
        self.layer2 = nn.Linear(64, 64, bias = True)
        self.layer3 = nn.Linear(64, 1, bias = True)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.1)
        self.batchnorm1 = nn.BatchNorm1d(64)
        self.batchnorm2 = nn.BatchNorm1d(64)
    
    def forward(self, inputs):
        x = self.relu(self.layer1(inputs))
        x = self.batchnorm1(x)
        x = self.relu(self.layer2(x))
        x = self.batchnorm2(x)
        x = self.dropout(x)
        x = self.layer3(x)
        return x

        

In [60]:
epochs = 1001
print_epoch = 100
lr = 1e-2

model = binaryClassification()
model.to(device)
print(model)
BCE = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = lr)

binaryClassification(
  (layer1): Linear(in_features=8, out_features=64, bias=True)
  (layer2): Linear(in_features=64, out_features=64, bias=True)
  (layer3): Linear(in_features=64, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (batchnorm1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)


In [65]:
def accuracy(y_pred, y_test):
    y_pred_tag = torch.round(torch.sigmoid(y_pred))
    # print(y_pred_tag)
    correct_results_sum = (y_pred_tag == y_test).sum().float()
    # print(correct_results_sum)
    acc = correct_results_sum / y_test.shape[0]
    acc = torch.round(acc * 100)
    return acc

In [67]:
for epoch in range(epochs):
    iteration_loss = 0.
    iteration_accuracy = 0.
    
    model.train()
    for i, data in enumerate(train_loader):
        X, y = data
        X, y = X.to(device), y.to(device)
        y_pred = model(X.float())
        loss = BCE(y_pred, y.reshape(-1, 1).float())
        
        iteration_loss += loss
        iteration_accuracy += accuracy(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    if epoch % print_epoch == 0:
        print(f'Train: epoch: {epoch} - loss: {(iteration_loss/(i+1)):.5f}; acc: {(iteration_accuracy/(i+1)):.3f}')
    
    iteration_loss = 0.
    iteration_accuracy = 0.
    model.eval()
    for i, data in enumerate(test_loader):
        X, y = data
        X, y = X.to(device), y.to(device)
        y_pred = model(X.float())
        loss = BCE(y_pred, y.reshape(-1, 1).float())
        
        iteration_loss += loss
        iteration_accuracy += accuracy(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    if epoch % print_epoch == 0:
        print(f'Test: epoch: {epoch} - loss: {(iteration_loss/(i+1)):.5f}; acc: {(iteration_accuracy/(i+1)):.3f}')
    

Train: epoch: 0 - loss: 0.41724; acc: 82.111
Test: epoch: 0 - loss: 0.41278; acc: 80.000
Train: epoch: 100 - loss: 0.42368; acc: 77.556
Test: epoch: 100 - loss: 0.41853; acc: 80.750
Train: epoch: 200 - loss: 0.49502; acc: 77.889
Test: epoch: 200 - loss: 0.41190; acc: 81.500
Train: epoch: 300 - loss: 0.48342; acc: 77.556
Test: epoch: 300 - loss: 0.38376; acc: 81.500
Train: epoch: 400 - loss: 0.39755; acc: 84.778
Test: epoch: 400 - loss: 0.38068; acc: 80.750
Train: epoch: 500 - loss: 0.39887; acc: 79.667
Test: epoch: 500 - loss: 0.39038; acc: 82.500
Train: epoch: 600 - loss: 0.41103; acc: 79.111
Test: epoch: 600 - loss: 0.37980; acc: 82.500
Train: epoch: 700 - loss: 0.41751; acc: 81.333
Test: epoch: 700 - loss: 0.44163; acc: 79.250
Train: epoch: 800 - loss: 0.41535; acc: 77.111
Test: epoch: 800 - loss: 0.40436; acc: 81.250
Train: epoch: 900 - loss: 0.41695; acc: 76.222
Test: epoch: 900 - loss: 0.37890; acc: 82.250
Train: epoch: 1000 - loss: 0.37916; acc: 79.000
Test: epoch: 1000 - loss: 

In [ ]:
y_pred_tag = torch.round(torch.sigmoid(y_pred))
# print(y_pred_tag)
correct_results_sum = (y_pred_tag == y_test).sum().float()
# print(correct_results_sum)
acc = correct_results_sum / y_test.shape[0]
acc = torch.round(acc * 100)

In [68]:
for i, data in enumerate(train_loader):
        X, y = data
        X, y = X.to(device), y.to(device)
        y_pred = model(X.float())

In [69]:
X

tensor([[ 0.0570,  1.6011,  0.0622, -0.4102,  0.7528, -0.2733, -0.3685, -0.0368],
        [-1.1644,  0.2299, -0.0400, -0.0941,  0.8533, -0.1711,  2.7238, -0.6983]],
       device='cuda:0')

In [70]:
y

tensor([[1.],
        [1.]], device='cuda:0')

In [71]:
y_pred

tensor([[ 1.7397],
        [-0.6675]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [72]:
y_pred_tag = torch.round(torch.sigmoid(y_pred)); y_pred_tag

tensor([[1.],
        [0.]], device='cuda:0', grad_fn=<RoundBackward0>)

In [73]:
correct_results_sum = (y_pred_tag == y_test); correct_results_sum

False

1